'use client'
/* eslint-disable react-hooks/set-state-in-effect */

import { FormEvent, useEffect, useState } from 'react'
import { apiRouter } from '@/lib/api'

type Member = { recruiterId: string; email: string; role?: string; companyRole?: string }
const roles = ['hr_manager', 'recruiter', 'hiring_manager']
export default function MembersPage() { const [members, setMembers] = useState<Member[]>([]); const [email, setEmail] = useState(''); const [role, setRole] = useState('recruiter'); const [message, setMessage] = useState(''); const [pending, setPending] = useState(false)
  async function load() { const response = await apiRouter.companies.members(); const data = await response.json().catch(() => ({})); if (response.ok) setMembers(data.members ?? []); else setMessage(data.error?.message ?? data.message ?? 'Could not load members.') }
  useEffect(() => { load() }, [])
  async function invite(event: FormEvent) { event.preventDefault(); setPending(true); setMessage(''); const response = await apiRouter.companies.invite({ email, role }); const data = await response.json().catch(() => ({})); setMessage(response.ok ? 'Invitation sent.' : data.error?.message ?? data.message ?? 'Could not send invitation.'); if (response.ok) setEmail(''); setPending(false) }
  async function update(member: Member, nextRole: string) { const response = await apiRouter.companies.updateMember(member.recruiterId, { role: nextRole }); if (response.ok) load(); else { const data = await response.json().catch(() => ({})); setMessage(data.error?.message ?? data.message ?? 'Could not update member.') } }
  async function remove(member: Member) { if (!window.confirm(`Remove ${member.email} from this company?`)) return; const response = await apiRouter.companies.removeMember(member.recruiterId); if (response.ok) load(); else setMessage('Could not remove member.') }
  return <main className="mx-auto max-w-6xl px-6 py-10 md:px-10"><div className="mb-8"><p className="text-sm font-semibold text-primary">Company settings</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">Team members</h1><p className="mt-2 max-w-2xl text-muted-foreground">Invite and manage workspace members. Owner-only permissions are enforced by the backend.</p></div>{message && <p className="mb-5 rounded-xl bg-muted p-3 text-sm">{message}</p>}<div className="grid gap-6 lg:grid-cols-[1fr_360px]"><section className="overflow-hidden rounded-3xl border bg-card"><div className="border-b px-6 py-5"><h2 className="font-semibold">Workspace members</h2></div>{members.length === 0 ? <p className="p-8 text-sm text-muted-foreground">No members found.</p> : <div className="divide-y">{members.map((member) => <div key={member.recruiterId} className="flex flex-col gap-4 px-6 py-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{member.email}</p><p className="mt-1 text-xs capitalize text-muted-foreground">{String(member.role ?? member.companyRole ?? 'member').replaceAll('_', ' ')}</p></div><div className="flex flex-wrap items-center gap-2"><select defaultValue={member.role ?? member.companyRole ?? 'recruiter'} onChange={(event) => update(member, event.target.value)} className="rounded-lg border bg-background px-2 py-2 text-xs">{roles.map((item) => <option key={item} value={item}>{item.replaceAll('_', ' ')}</option>)}</select><button onClick={() => remove(member)} className="rounded-lg border px-3 py-2 text-xs text-destructive">Remove</button></div></div>)}</div>}</section><form onSubmit={invite} className="flex h-fit flex-col gap-5 rounded-3xl border bg-card p-6"><div><h2 className="font-semibold">Invite a member</h2><p className="mt-1 text-sm text-muted-foreground">Use the email and role fields expected by the backend.</p></div><label className="flex flex-col gap-2 text-sm font-medium">Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="rounded-xl border bg-background px-3 py-3" /></label><label className="flex flex-col gap-2 text-sm font-medium">Role<select value={role} onChange={(event) => setRole(event.target.value)} className="rounded-xl border bg-background px-3 py-3">{roles.map((item) => <option key={item} value={item}>{item.replaceAll('_', ' ')}</option>)}</select></label><button disabled={pending} className="rounded-xl bg-primary px-4 py-3 font-medium text-primary-foreground">{pending ? 'Sending…' : 'Send invitation'}</button></form></div></main>
}
