'use client'

import Link from 'next/link'

type Job = { title: string; status?: string; company_name?: string; companyName?: string; location?: string; employment_type?: string; salary_min?: number; salary_max?: number; description?: string; deadline?: string; attributes?: unknown; screening_questions?: { text: string }[] }
import { useParams, useRouter } from 'next/navigation'
import { useEffect, useState } from 'react'
import { apiRouter } from '@/lib/api'

export default function JobDetailPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const [job, setJob] = useState<Job | null>(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [pending, setPending] = useState(false)
  useEffect(() => { apiRouter.public.job(id).then(async (r) => { const data = await r.json().catch(() => ({})); setJob(data.job ?? data); }).finally(() => setLoading(false)) }, [id])
  async function action(request: () => Promise<Response>, success: string) { setPending(true); setMessage(''); const r = await request(); const data = await r.json().catch(() => ({})); if (r.status === 401) router.push(`/login?next=/jobs/${id}`); else setMessage(r.ok ? success : data.error?.message ?? data.message ?? 'Unable to complete action.'); setPending(false) }
  if (loading) return <main className="mx-auto max-w-5xl px-6 py-16 text-muted-foreground">Loading job…</main>
  if (!job) return <main className="mx-auto max-w-5xl px-6 py-16"><h1 className="text-2xl font-semibold">Job not found</h1><Link href="/jobs" className="mt-4 inline-block text-primary">Back to jobs</Link></main>
  const salary = job.salary_min || job.salary_max ? `${job.salary_min ?? ''}${job.salary_min && job.salary_max ? ' – ' : ''}${job.salary_max ?? ''}` : ''
  const attributes: string[] = job.attributes && typeof job.attributes === 'object' && !Array.isArray(job.attributes) ? Object.entries(job.attributes as Record<string, unknown>).filter(([, value]) => value).map(([key, value]) => `${key.replaceAll('_', ' ')}: ${String(value)}`) : Array.isArray(job.attributes) ? job.attributes.map((value) => String(value)) : []
  return <main className="min-h-screen bg-background"><header className="border-b bg-card"><div className="mx-auto max-w-5xl px-6 py-4"><Link href="/jobs" className="text-sm font-medium text-primary">← Back to jobs</Link></div></header><article className="mx-auto max-w-5xl px-6 py-12"><div className="grid gap-8 lg:grid-cols-[1fr_300px]"><section><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">{job.status ?? 'Open position'}</p><h1 className="mt-3 text-5xl font-semibold tracking-tight">{job.title}</h1><p className="mt-3 text-lg text-muted-foreground">{job.company_name ?? job.companyName ?? 'Talent Hunt company'}</p><div className="mt-6 flex flex-wrap gap-2 text-sm text-muted-foreground">{[job.location, job.employment_type, salary && `$${salary}`].filter(Boolean).map((item) => <span key={String(item)} className="rounded-full bg-muted px-3 py-1 capitalize">{String(item).replaceAll('_', ' ')}</span>)}</div><div className="prose prose-slate mt-12 max-w-none whitespace-pre-wrap"><h2>About the role</h2><p>{job.description}</p>{attributes.length > 0 && <><h2>Role details</h2><ul>{attributes.map((item: string) => <li key={item}>{item}</li>)}</ul></>}{(job.screening_questions?.length ?? 0) > 0 && <><h2>Application questions</h2><ol>{job.screening_questions?.map((q) => <li key={q.text}>{q.text}</li>)}</ol></>}</div></section><aside className="h-fit rounded-3xl border bg-card p-6 shadow-sm"><h2 className="font-semibold">Interested in this role?</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Apply or save this job to revisit it later.</p><div className="mt-6 flex flex-col gap-3"><button disabled={pending} onClick={() => action(() => apiRouter.applicants.apply({ jobIds: [id], answers: {} }), 'Application submitted.')} className="rounded-xl bg-primary px-4 py-3 font-medium text-primary-foreground">Apply now</button><button disabled={pending} onClick={() => action(() => apiRouter.applicants.addShortlist(id), 'Saved to shortlist.')} className="rounded-xl border px-4 py-3 font-medium">Save job</button></div>{message && <p className="mt-4 text-sm text-muted-foreground">{message}</p>}{job.deadline && <p className="mt-8 border-t pt-5 text-sm text-muted-foreground">Apply by {new Date(job.deadline).toLocaleDateString()}</p>}</aside></div></article></main>
}
