'use client'
/* eslint-disable react-hooks/set-state-in-effect */

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { apiRouter } from '@/lib/api'

type Interview = { scheduled_at: string }
type Application = { id: string; applicant_name?: string; email?: string; headline?: string; job_title?: string; status?: string; latest_interview?: Interview | null }
const stages = ['applied', 'screening', 'interview', 'final_interview', 'offer', 'hired', 'rejected']
const labels: Record<string, string> = { applied: 'Applied', screening: 'Screening', interview: 'Interview', final_interview: 'Final interview', offer: 'Offer', hired: 'Hired', rejected: 'Rejected' }

export default function ApplicantsPage() {
  const [pipeline, setPipeline] = useState<Record<string, Application[]>>({}); const [error, setError] = useState(''); const [busy, setBusy] = useState(''); const [filter, setFilter] = useState('all')
  async function load() { const response = await apiRouter.applications.pipeline(); const data = await response.json().catch(() => ({})); if (!response.ok) setError(data.error?.message ?? data.message ?? 'Unable to load pipeline.'); else setPipeline(data.pipeline ?? {}) }
  useEffect(() => { load() }, [])
  async function move(id: string, stage: string) { setBusy(id); setError(''); const response = await apiRouter.applications.moveStage(id, stage); if (!response.ok) { const data = await response.json().catch(() => ({})); setError(data.error?.message ?? data.message ?? 'That transition is not allowed.') } else await load(); setBusy('') }
  return <main className="mx-auto max-w-[1500px] px-5 py-8 md:px-8"><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-semibold text-primary">Recruiter workspace</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">Hiring pipeline</h1><p className="mt-2 text-muted-foreground">Each stage is an independent column with readable candidate cards.</p></div><button onClick={load} className="rounded-xl border px-4 py-2 text-sm">Refresh</button></div><div className="mb-5 flex gap-2 overflow-x-auto pb-1">{['all', ...stages].map((stage) => <button key={stage} onClick={() => setFilter(stage)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm ${filter === stage ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'}`}>{stage === 'all' ? 'All candidates' : labels[stage]}</button>)}</div>{error && <p className="mb-5 rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<div className="grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-4 2xl:grid-cols-7">{stages.map((stage) => <section key={stage} className={`min-w-0 rounded-2xl border bg-muted/30 p-4 ${filter !== 'all' && filter !== stage ? 'hidden' : ''}`}><div className="mb-4 flex items-center justify-between"><h2 className="truncate font-semibold">{labels[stage]}</h2><span className="rounded-full bg-background px-2 py-1 text-xs text-muted-foreground">{pipeline[stage]?.length ?? 0}</span></div><div className="flex flex-col gap-3">{(pipeline[stage] ?? []).map((item) => <article key={item.id} className="min-w-0 rounded-xl border bg-card p-4 shadow-sm"><h3 className="break-words font-semibold">{item.applicant_name ?? item.headline ?? item.email ?? 'Applicant'}</h3><p className="mt-2 break-words text-sm text-muted-foreground">{item.job_title ?? 'Application'}</p>{item.latest_interview && <p className="mt-3 rounded-lg bg-muted px-3 py-2 text-xs text-muted-foreground">Interview {new Date(item.latest_interview.scheduled_at).toLocaleString()}</p>}<div className="mt-4 flex flex-col gap-2"><Link href={`/dashboard/applicants/${item.id}`} className="text-sm font-medium text-primary">Open candidate review</Link>{!['hired', 'rejected'].includes(stage) && <select aria-label={`Move ${item.id}`} disabled={busy === item.id} defaultValue="" onChange={(event) => event.target.value && move(item.id, event.target.value)} className="w-full rounded-lg border bg-background px-2 py-2 text-xs"><option value="">Move to…</option>{stages.filter((next) => next === 'rejected' || stages.indexOf(next) > stages.indexOf(stage)).map((next) => <option key={next} value={next}>{labels[next]}</option>)}</select>}</div></article>)}{!pipeline[stage]?.length && <p className="py-10 text-center text-xs text-muted-foreground">No candidates</p>}</div></section>)}</div></main>
}
